### ISSUE TITLE
[Crash] 

### ISSUE THREAD

**Issue by NattoRiisa** [NeutronForge/little-johns-1.21.x#2]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'little_johns' at 'com.echo.little_johns.LittleJohns'!
(Crash report also contains all the mods that are loaded in)
[crash-2024-10-30_19.55.04-client.txt](https://github.com/user-attachments/files/17571861/crash-2024-10-30_19.55.04-client.txt)

**Comment by NeutronForge** [comment]
The mod doesnt support 1.21, 1.21.1 or 1.21.2 since there were quite some changed in the code base
As of now, only 1.21.3 is supported
